default:
  retry:
    max: 1
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

before_script:
  - docker info

stages:
  - test

unit_tests:
  stage: test
  services:
    - docker:19-dind
  script:
    - docker info
    - docker build . --tag sdo-omniauth-ping-one
    - docker run --rm --name="sdo-omniauth-ping-one-cont" sdo-omniauth-ping-one
  tags:
    - sdo-default-runner
  only:
    - master
