# Note: This is not working yet. Codeberg does not have ruby/setup-ruby action https://codeberg.org/actions
#       and currently the runner is complaining about not really being a GitHub Action runner.
#       Thus we are currently relying on actual GitHub Actions for this repo: https://github.com/Schmidt-DevOps/OmniAuth-PingOne/actions

name: Ruby

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: https://github.com/ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build and test
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec
