### How to use:
### 1. Do what oauth2_00 says.
### 3. Run this file.
### 4. Note the access and refresh token. Update the env file accordingly.

POST {{host}}/as/token.oauth2
Accept: application/json
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}&client_secret={{client_secret}}&code={{code}}&state={{state}}&redirect_uri={{redirect_uri}}&grant_type=authorization_code

> {%
client.test("Expect HTTP status 200 on login form", function() {
  var type = response.contentType.mimeType;
  client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
  client.assert(response.status === 200, "Expected HTTP status 200");
});
%}
